version: '3.1'
services:
  server:
    build: .
    image: pricing-engine
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abc1234
      - POSTGRES_DB=pricing
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_PASSWORD=
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GIN_MODE=release
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc1234
      POSTGRES_DB: pricing
    expose:
      - "5432"
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  redis:
    image: redis
    command: redis-server
    expose:
      - "6379"