BEGIN;

-- Base tables

CREATE TABLE IF NOT EXISTS rules (
    id SERIAL PRIMARY KEY,
    is_percent BOOLEAN NOT NULL,
    amount INT NOT NULL
);

CREATE TABLE IF NOT EXISTS cities (
    id SERIAL PRIMARY KEY,
    name VARCHAR(3) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS airlines (
    id SERIAL PRIMARY KEY,
    name VARCHAR(3) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS suppliers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS agencies (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

-- Relational tables

CREATE TABLE IF NOT EXISTS rule_routes (
    rule_id INT NOT NULL
        REFERENCES rules(id) 
        ON DELETE CASCADE,
    origin_id INT NOT NULL 
        REFERENCES cities(id),
    destination_id INT NOT NULL
        REFERENCES cities(id)
);

CREATE TABLE IF NOT EXISTS rule_airlines (
    rule_id INT NOT NULL
        REFERENCES rules(id) 
        ON DELETE CASCADE,
    airline_id INT NOT NULL 
        REFERENCES airlines(id)
);

CREATE TABLE IF NOT EXISTS rule_suppliers (
    rule_id INT NOT NULL
        REFERENCES rules(id) 
        ON DELETE CASCADE,
    supplier_id INT NOT NULL 
        REFERENCES suppliers(id)
);

CREATE TABLE IF NOT EXISTS rule_agencies (
    rule_id INT NOT NULL
        REFERENCES rules(id) 
        ON DELETE CASCADE,
    agency_id INT NOT NULL 
        REFERENCES agencies(id)
);

-- Populate tables

INSERT INTO cities (name)
VALUES
    ('*'),
    ('ABD'),('AEU'),('AWZ'),('AKW'),('AJK'),('ADU'),
    ('PGU'),('BBL'),('BXR'),('BND'),('ZBR'),('BDH'),
    ('MRX'),('IAQ'),('XBJ'),('BJB'),('DEF'),('FAZ'),
    ('GCH'),('GBT'),('HDM'),('IIL'),('IHR'),('IFN'),
    ('JAR'),('KNR'),('JYR'),('KLM'),('PYK'),('KKS'),
    ('KER'),('KSH'),('KHK'),('KHD'),('KHY'),('KIH'),
    ('LFM'),('LRR'),('LVP'),('ACP'),('MHD'),('NSH'),
    ('OMH'),('PFQ'),('GZW'),('GSM'),('RJN'),('RZR'),
    ('RAS'),('AFZ'),('SDG'),('CKT'),('SRY'),('CQD'),
    ('RUD'),('SYZ'),('SXI'),('SYJ'),('TCX'),('TBZ'),
    ('THR'),('YES'),('AZD'),('ACZ'),('ZAH'),('JWN'),
    ('BUZ'),('IMQ'),('JSK');

INSERT INTO airlines (name)
VALUES
    ('EP'),('W5'),('HH'),('QB'),('IV'),('NV'),('Y9'),
    ('TF'),('ZV'),('IR'),('I3'),('IS'),('JI'),('B9'),
    ('AK'),('HE'),('H8'),('VA'),('VR'),('PY'),('SA'),
    ('SE'),('RV'),('FP'),('ZZ'),('SR'),('PA'),('IU'),
    ('RI'),('PYA'),('PRS'),('FPI'),('KIA'),('IRU'),('IRZ');

INSERT INTO agencies (name)
VALUES
    ('MARCO_CHARTER'),('DONYA_GASHT'),('ARAZ_GASHT'),
    ('HOORTASH_PARVAZ'),('NOOR_HAN'),('NEDA_PARVAZ'),
    ('DAYANA_GASHT'),('SAVIS_SAFAR'),('ARYAN_RASHA'),
    ('KARAJ_GASHT'),('FLY_TICKET'),('GHAZAL_PARVAZ'),
    ('ALMAS_GASHT'),('DONYA_GOSTAR'),('KAHAR_GASHT'),
    ('KAROON_SEIR'),('HAMRAH_SETAREGAN'),('CAPITAN'),
    ('HAFT_ASEMAN_NILI_KISH'),('SHADI_AVARAN_SAFAR'),
    ('236'),('ELIN_SEIR'),('MEHVAR_TALAEI_KHAVARAN'),
    ('ARYA_RESERVE'),('AZARBAL_IRANIAN'),('ALAEDIN'),
    ('PARSAMAD'),('MIRAS_PERSIA'),('7OWRANG_SYSTEM'),
    ('FARANAMA_IRANIAN'),('AVAYE_GARDESHGARAN_YAAS'),
    ('GHASR_DARIUSH_KABIR'),('SEPEHR_NAMAY_SEPAHAN'),
    ('ASEMAN_PARVAZ_IRANIAN'),('TAKSETARE_PASDARAN'),
    ('AYSAN_PARVAZ_BAKU'),('PARASTOO_PARVAZ_ASEMAN'),
    ('ELAHE_ALMAS'),('BORNA_GASHT'),('SEIRAN_GASHT'),
    ('ASIA_SEIR'),('HALI_TOUR'),('BALAN_MEHR_GASHT'),
    ('EHSAN_PEYMA_ARIAEI'),('DELTABAN'),('KARVANIK'),
    ('ATI_MASHHAD'),('SANAM_PARVAZ'),('RAHBAL_TEST'),
    ('FARAZ_GASHT_ASEMAN'),('ADINE_GASHT_ALIGHAPOU'),
    ('PARS_PARVAZ_JONOOB'),('BORJE_SEFID'),('YASNA'),
    ('SAHLAN_GASHT'),('EMAM_REZA'),('SHENASA_GASHT'),
    ('PEDMA'),('NADIA_PARVAZ'),('VANIA_PARVAZ_PARS'),
    ('TAHA_PARVAZ_ASEMAN'),('TAMASHA_IRANIAN_ATLAS'),
    ('AKRAMI_HOTELS_GROUP'),('JONOOB_SHARGH_KERMAN'),
    ('FARAZ_KISH'),('JANAM_GASHT'),('PARASTOO_SEIR'),
    ('VANIA_PARVAZ'),('FLY_CHARTER'),('GASHT_NAVID'),
    ('MOHTASHAM_SAFAR_KASHAN'),('HAGHA_SEIR_REZVAN'),
    ('CHARTER_724'),('MEHRYAR_PARVAZ'),('TOP_TOURS'),
    ('BEHESHT_REYHANE_IRANIAN'),('YAZD_TOURS_GROUP'),
    ('MANASEIR_KOOSHA_KISH'),('PAYTAKHT_GASHT_ARYA'),
    ('OXIN_GASHT'),('PADIDEH_PARVAZ'),('SALAR_KISH'),
    ('MAHAN_TOUR'),('NASIM_BEHESHT'),('TAMIM_GASHT'),
    ('IRANGARDI_VA_JAHANGARDI'),('FARATAR_AZ_ZAMIN'),
    ('PAYA_SEIR'),('ARSHIAN_SHIRAZ'),('MITRA_GASHT'),
    ('ALVIN'),('JAHAN_GASHT_IRANIAN'),('RADAN_SEIR'),
    ('BESAT'),('ASEMAN_PORKHATERE'),('RAHAD_ASEMAN'),
    ('GOROOH_SAMIN'),('RAHAD_KISH'),('MEHRAD_GASHT'),
    ('PARVAZ_GASHT_ASEMAN_ABI'),('FARANEGAR_RADINA'),
    ('MANIA_GASHT'),('DIYAKO_PARVAZ'),('TEST_RAVIS'),
    ('KISH_PARVAZ'),('BARAD_PARVAZ'),('LACHIN_SEIR'),
    ('TAGHDIS_PARVAZ'),('IRAN_AIRTOUR'),('FARGASHT'),
    ('ARYABAN_KISH'),('FAZA_GASHT'),('ASEMAN_SEPID'),
    ('CHAPAR_SEIR'),('FERESHTE_SEIR'),('ELIA_GASHT'),
    ('MEHR_O_MAH'),('MOSALAS_PARVAZ'),('ASA_PARVAZ'),
    ('SAFIR_SADEGHIYE_TOOS'),('SHAHIN_GASHT_TEHRAN'),
    ('TAJALI_NOUR'),('ADAM_VA_HAVA'),('ASEMAN_FATH'),
    ('HAMNAVAZ_ASEMAN_ABI106'),('MALEK_SEIR_PARVAZ'),
    ('ELHAM_SEIR'),('HAFT_ORANG_MOGHIM'),('YADEMAN'),
    ('PISHTAZ_ARYA'),('NOORA_SEIR'),('HEDIE_PARVAZ'),
    ('ARSAN_SEIR'),('MIRDAMAD'),('BEHMANESH_PARVAZ'),
    ('ESPAD_GASHT'),('PARVAZ_CHARTER'),('SAYE_SEIR'),
    ('MEHRAB_SEIRKISH'),('ARYA_NAHAD'),('ARAM_SEIR'),
    ('GARDESHGARI'),('SAINA_SEIR110'),('ADONIS_BAL'),
    ('DEHPOOYE'),('SAFAR_SEIR_PARS'),('RADIN_GASHT'),
    ('MOHAJER_PARS_BOUSHEHR'),('NASIM_BEHESHT_AMIN'),
    ('MARKAZ_TOUR'),('JANAN_GASHT'),('ATRIA_PARVAZ'),
    ('AFARINESH_KHATE_SEVOM_PARVAZ'),('BALON_SEFID'),
    ('KATIBE_GASHT'),('HAMGAMAN'),('BISTOON_TRAVEL'),
    ('TIAM_GASHT'),('KEYVAN_PARVAZ'),('PARSA_GASHT'),
    ('TAKHT_KOOROSH_IRANIAN'),('SETARE_SHAB_FARBOD'),
    ('KHATIB_SEIR'),('BEHGASHT_ARYA'),('AMAJ_GASHT'),
    ('TABAN_24'),('HOUT_CHAKAVAK'),('MEHRYAR_GASHT'),
    ('SHAHED'),('PERSIA_SEIR_KANGAN'),('SAMEN_TOUR'),
    ('GARDESHGARAN'),('MEHRAB_GASHT'),('OWJ_PARVAZ'),
    ('CHOOBIN_PARVAZ_ARIA'),('AFTAB_DERAKHSHAN_DEY'),
    ('MANA_PARVAZ'),('SHAGHAYEGH_ABI'),('ERAM_KISH'),
    ('MAHAN_SEIR_SAM'),('DORIN_SEIR'),('ATRIN_SEIR'),
    ('ARTIN_GASHT'),('MOSALAT_SEIR'),('DARA_PARVAZ'),
    ('HOMAY_SARZAMIN_PISHGAMAN'),('PARVAZ_PARDAZAN'),
    ('HELMA_GASHT_YAZD'),('SAFIR_NOOR'),('SAERSEIR'),
    ('AVINA_SEIR'),('TAK_SETARE_NILOOFAR'),('KITOO'),
    ('KAVOSHGARAN_TAHA_PARVAZ'),('DAYAN_SAFAR_KISH'),
    ('HOURSHID_ASEMAN_ABI'),('DARIUSH_PARVAZ_GHARN'),
    ('PARSIAN_SIAHAT_ESPADANA'),('ARTIN_GASHT_KISH'),
    ('PERGAS_GASHT'),('546'),('DONYAYE_HAFT_EGHLIM'),
    ('SEPIDEH_PARVAZ_MASHHAD'),('FARAZ_KISH_OFFICE'),
    ('MAHAN_MEHR_IRANIAN'),('DORSA_GASHT_ALIGHAPOO'),
    ('MOGHIM_TEST_AGENCY'),('ARIYAIAN_JAHAN_GOSTAR'),
    ('PADIDEH81'),('AYAN_PARVAZ'),('HAMSAFAR_GASHT'),
    ('MAHSHID_GASHT'),('MALEK_SEIR'),('BAAL_TALAYI'),
    ('MOIEN_DARBARI'),('AFSHID_GASHT'),('KISH_IRAN'),
    ('CHATR_PARVAZ'),('RAHE_ESFAHAN'),('KIA_PARVAZ'),
    ('PAYA_SYSTEM'),('KIMIA_PARVAZ'),('NADIA_GASHT'),
    ('BESAT_KISH'),('ROZ_GASHT'),('SAFAE_BE_ROYAHA'),
    ('IDEAL_SAFAR_PARSIAN'),('HADIGHE_PARVAZ_MAHAN'),
    ('ATIN_GROUP'),('ELIMA'),('NIYAYESH_SEIR_SAFAR'),
    ('8BOOK'),('DARIUSH_SIAHAT'),('PERSIAN_CHARTER'),
    ('RAD_TRAVEL'),('AFAGH_SEIR'),('MARDUKH_TRAVEL'),
    ('HAFT_ASEMAN'),('HOORAD_GASHT'),('FAHIM_GASHT'),
    ('CARYAR'),('SAFINE_PARVAZ_NEGIN'),('NESA_SEIR'),
    ('BALE_SAFAR_AHWAZ'),('IRANIAN_PARVAZ_AREZOOHA'),
    ('PAGAS_GASHT'),('UNKNOWN'),('ARTIMAN_IDE_KISH'),
    ('AVA_SEIR'),('ARSHIAN_SALAR'),('GHASR_DARIUSH'),
    ('AYSAN_PARVAZ_PARS'),('NASIM_BEHESHT_KHORASAN'),
    ('BENIS_TRAVEL'),('FARJAM_PARVAZ'),('TAKSETARE'),
    ('SAMYAR_TOOS'),('SHAHAB_TRAVEL'),('HAGHA_SEIR'),
    ('HAFT_VADI'),('BAMDAD_AHVAZ'),('KHAYYAM_GASHT'),
    ('ARIOBAL_KISH'),('SARA_SEIR'),('PARS_HOLIDAYS'),
    ('GARDESHGARAN_ZAMAN'),('SABZ_GASHT'),('TASNIM'),
    ('DARKOOB_ASEMAN_ABI'),('BARBOD_PARVAZ'),('906'),
    ('RAHYAB'),('ESHKEVARI_TOUR'),('OMID_PARVAZ_OJ'),
    ('ELVA_SEIR'),('SEIR_FARS'),('AFTAB_DERAKHSHAN'),
    ('GOLGASHT_JONOOB_SHARGH'),('ARSH_ASEMAN_VISTA'),
    ('GOLFAM_SAFAR'),('ROOBIN24'),('SEKHAVAT_GASHT'),
    ('ATRAK_AIRLINE'),('MERSA'),('HAGHASEIR_REZVAN'),
    ('CHAKAVAK'),('SHOKOOH_PAEEZ'),('ASEMAN_HAFTOM'),
    ('RAZ_PARVAZ_JAHAN'),('ARSHAN_PARVAZ'),('SKY24'),
    ('AMIN_GASHT'),('SEPID_PARVAZ'),('VIHAN_TRAVEL'),
    ('BALAN_GASHT'),('PALIZ_SEIR'),('ANA_SEIR_PARS'),
    ('2'),('ELENA_SEIR_PARS'),('PAEEZ_PARVAZ_QESHM'),
    ('NASIM_SAHAR_AFARIN'),('SETARE_MOSAFERAN_IRSA'),
    ('ARSH_ASEMAN_VAHID'),('CHOOBIN_PARVAZ'),('754'),
    ('HELIA_MEHR'),('PARASTOOYE_KAVIR'),('BAD_SABA'),
    ('ESFAHAN_GASHT'),('OMIDAN_PARVAZ'),('BAL_SEIR'),
    ('SARANG_PARVAZ_IRANIAN'),('SHADI_SEIR_IRANIAN'),
    ('ARYAN_GASHT_ARQAVAN'),('IRANIAN_BASTAN_SAFAR'),
    ('AZIN_GASHT'),('PARDIS_PARVAZ'),('SAEE_TEHRAN'),
    ('ABTIN_GASHT_PARS'),('SAFARANE_MASHREGH_ZAMIN'),
    ('SEPEHRHUB'),('GEORGIA_HOLIDAY'),('ROZ_PARVAZ'),
    ('MOGHTADER_SEIR_IRANIAN'),('SAFARHAYE_ALIBABA'),
    ('SEPIDEH_PARVAZ_SHIRAZ'),('PISHGAMAN_RAH_GITI'),
    ('TICKETING'),('ERAM_PARS_KISH'),('MATIN_GASHT'),
    ('GARDESHGARAN_SHIRAZ'),('YADEMAN_PERSIA_GASHT'),
    ('FARDAD_GASHT'),('FAKHTE_GASHT'),('ILIA_GASHT'),
    ('TEHRAN_SHAFAGH_PERSIA'),('HAGHA_SEIR_MASHHAD'),
    ('HAMNAVAZ_ASEMANABI'),('KHAZAR_PARVAZ_CASPIAN'),
    ('GOLZAR_GASHT_PARSEH'),('FOROOZAN_GASHT_AHVAZ'),
    ('ARIO_PARVAZ'),('TAHA_PARVAZ'),('SOORENA_SEIR'),
    ('HAVANAVARDAN_KABIR_ASEMAN'),('TIROOZH_PARVAZ'),
    ('SAINA_SEIR24'),('HEJRAT_ASEMAN'),('MOUD_MEHR'),
    ('PAYDOOS'),('HAMAN_SEIR_YAZD'),('GASHTA_GASHT'),
    ('TABRIZ_TOURISTS_GROUP'),('NASIM_BEHESHT_KISH'),
    ('PERSIAN_PARVAZ_KAVIR'),('DONYA_GOSTAR_SHIRAZ'),
    ('MOGHIM_24'),('PARHAM_GASHT'),('SARZAMIN_PARS'),
    ('ARMANSHID'),('SADRA_GASHT_GITI'),('FLY_SADAN'),
    ('ATLAS_YAZD'),('MAHBAL_SEIR'),('SABZINE_GASHT'),
    ('ELIMA_GASHT'),('SATRAP_TABRIZ'),('FARA_GASHT'),
    ('PARHAM_SEIR_SHARGH'),('KHAYYAM_GASHT_IRANIAN'),
    ('PARVAZ_EMAD_GASHT'),('DARIUSH_SIAHAT_MASHHAD'),
    ('FARD_PARVAZ'),('IMAN_AMIN'),('SEPEHR_SAYAHAN'),
    ('AALI_GASHT'),('SAFIR_IRAQ'),('ARSHIAN_PARVAZ'),
    ('CHOOBIN'),('ARYA_SILK_BASTAN'),('AVISA_GASHT'),
    ('SHAHRAN_GASHT'),('KOSAR_GASHT'),('HAMAN_SEIR'),
    ('ARYAN_PARVAZ'),('JOME_GASHT'),('MARCO_TRAVEL'),
    ('KEIHAN_GASHT'),('HOOR_GASHT'),('JAHAN_PARVAZ'),
    ('RAH_TAMADON_PARSIAN'),('IRSA_90_SEIR_PARVAZ'),
    ('KHORSHID_SEIR_TOOS'),('SAFARYAR_GOHAR_TOOS'),
    ('SAINA_GASHT_ZORAGH'),('MAHROKH_GASHT_MAHAN'),
    ('SEPID_PARVAZ_TOOS'),('RATA_PARVAZ_IRANIAN'),
    ('TOOTIA_SEIR_SAADAT'),('DAYAN_SEIR_ESPADAN'),
    ('SETARE_BORJS_EFID'),('SARZAMIN_KHATEREHA'),
    ('ARSHAM_MEHR_IRANIAN'),('TAKSETARE_SYSTEM'),
    ('ARIA_PARVAZ_MASHHAD'),('SEPEHR_SEIR_TOOS'),
    ('GHABILEH_ASEMAN_ABI'),('MOGHTADER_GASHT'),
    ('DOLPHIN_SEIR_QESHM'),('ADINE_SAFAR_KISH'),
    ('SABZ_GASHT_OMID'),('MOGHIM_TEST2_AGENCY'),
    ('OMID_PARVAZ_MEHR'),('AMIRAN_PARVAZ_SAM'),
    ('PARS_PARVAZ_MEHR'),('SAFAR_ASOON_KISH'),
    ('ASEMAN_PORSETARE'),('SABA_GASHT_MAHAN'),
    ('RESPINA_MASHHAD'),('HAMTA_PARVAZ_ILIA'),
    ('TASHRIFAT_PARVAZ'),('PAYAM_TOSEE_SABA'),
    ('SUNNY_PARVAZ_PARS'),('AMITIS_BAL_PARS'),
    ('RAHBAL_ASEMAN'),('BESAT_SEIR_KHORASAN'),
    ('SETARE_GONBAD'),('DATIS_5_GHARRE_TOOS'),
    ('SEPEHR_SEIR_IRIK'),('HOTEL_ERAM_KISH'),
    ('KOUROSH_TRAVEL'),('SEIR_ASEMAN_FARAZ'),
    ('NIKA_PARVAZ_PARS'),('GARDESHGARAN136'),
    ('ROSHANI_GASHT'),('BESAT_SEIR_IRANIAN'),
    ('BITA_TOUR_GROUP'),('TAMASHA_RAZ_GITI'),
    ('KIMIA_TOURIST_KISH'),('SHERVIN_GASHT'),
    ('FARA_GASHT_KUROSH'),('ERIKE_IRANIAN'),
    ('MEHRABAD_GASHT'),('SOORENA_SEIRKISH'),
    ('ARNA_SEIR_PERSIAN'),('TARHAN_PARVAZ'),
    ('ABTIN_GASHT_ARIA'),('KHOSROVAN_SEIR'),
    ('BAROKH_PARVAZ'),('MEHR_O_MAH_TRAVEL'),
    ('GARDESHGARI_NOOR'),('ASEMAN_IRANIAN'),
    ('SHAHIN_GASHT_KISH');
INSERT INTO suppliers (name)
VALUES
    ('FARANEGAR'),('ZAGROS'),('ATAA'),('CASPIAN'),
    ('CHARTEX'),('RAVIS'),('ASEMAN'),('AIRTOUR'),
    ('SEPEHRAN'),('MOGHIM'),('KARUN'),('SAHA'),
    ('QESHM-SOORINET'),('SEPEHR'),('MERAJ'),
    ('VARESH'),('KISHAIR'),('TABAN'),('PARSAIR');

COMMIT;